//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ISchool.WebService.Students")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Place8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject8Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccNumber {
            get {
                return this.AccNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNumberField, value) != true)) {
                    this.AccNumberField = value;
                    this.RaisePropertyChanged("AccNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place1 {
            get {
                return this.Place1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place1Field, value) != true)) {
                    this.Place1Field = value;
                    this.RaisePropertyChanged("Place1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place2 {
            get {
                return this.Place2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place2Field, value) != true)) {
                    this.Place2Field = value;
                    this.RaisePropertyChanged("Place2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place3 {
            get {
                return this.Place3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place3Field, value) != true)) {
                    this.Place3Field = value;
                    this.RaisePropertyChanged("Place3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place4 {
            get {
                return this.Place4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place4Field, value) != true)) {
                    this.Place4Field = value;
                    this.RaisePropertyChanged("Place4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place5 {
            get {
                return this.Place5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place5Field, value) != true)) {
                    this.Place5Field = value;
                    this.RaisePropertyChanged("Place5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place6 {
            get {
                return this.Place6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place6Field, value) != true)) {
                    this.Place6Field = value;
                    this.RaisePropertyChanged("Place6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place7 {
            get {
                return this.Place7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place7Field, value) != true)) {
                    this.Place7Field = value;
                    this.RaisePropertyChanged("Place7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place8 {
            get {
                return this.Place8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Place8Field, value) != true)) {
                    this.Place8Field = value;
                    this.RaisePropertyChanged("Place8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject1 {
            get {
                return this.Subject1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject1Field, value) != true)) {
                    this.Subject1Field = value;
                    this.RaisePropertyChanged("Subject1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject2 {
            get {
                return this.Subject2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject2Field, value) != true)) {
                    this.Subject2Field = value;
                    this.RaisePropertyChanged("Subject2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject3 {
            get {
                return this.Subject3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject3Field, value) != true)) {
                    this.Subject3Field = value;
                    this.RaisePropertyChanged("Subject3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject4 {
            get {
                return this.Subject4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject4Field, value) != true)) {
                    this.Subject4Field = value;
                    this.RaisePropertyChanged("Subject4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject5 {
            get {
                return this.Subject5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject5Field, value) != true)) {
                    this.Subject5Field = value;
                    this.RaisePropertyChanged("Subject5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject6 {
            get {
                return this.Subject6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject6Field, value) != true)) {
                    this.Subject6Field = value;
                    this.RaisePropertyChanged("Subject6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject7 {
            get {
                return this.Subject7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject7Field, value) != true)) {
                    this.Subject7Field = value;
                    this.RaisePropertyChanged("Subject7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject8 {
            get {
                return this.Subject8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject8Field, value) != true)) {
                    this.Subject8Field = value;
                    this.RaisePropertyChanged("Subject8");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudentByRange", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentByRangeResponse")]
        WindowsFormsApplication1.ServiceReference1.Student[] GetAllStudentByRange(int Start, int End);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudentByRange", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentByRangeResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Student[]> GetAllStudentByRangeAsync(int Start, int End);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentWithAcc", ReplyAction="http://tempuri.org/IStudentService/GetStudentWithAccResponse")]
        WindowsFormsApplication1.ServiceReference1.Student GetStudentWithAcc(string WACC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentWithAcc", ReplyAction="http://tempuri.org/IStudentService/GetStudentWithAccResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Student> GetStudentWithAccAsync(string WACC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentWithLikleyName", ReplyAction="http://tempuri.org/IStudentService/GetStudentWithLikleyNameResponse")]
        WindowsFormsApplication1.ServiceReference1.Student GetStudentWithLikleyName(string LNAME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentWithLikleyName", ReplyAction="http://tempuri.org/IStudentService/GetStudentWithLikleyNameResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Student> GetStudentWithLikleyNameAsync(string LNAME);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : WindowsFormsApplication1.ServiceReference1.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IStudentService>, WindowsFormsApplication1.ServiceReference1.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApplication1.ServiceReference1.Student[] GetAllStudentByRange(int Start, int End) {
            return base.Channel.GetAllStudentByRange(Start, End);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Student[]> GetAllStudentByRangeAsync(int Start, int End) {
            return base.Channel.GetAllStudentByRangeAsync(Start, End);
        }
        
        public WindowsFormsApplication1.ServiceReference1.Student GetStudentWithAcc(string WACC) {
            return base.Channel.GetStudentWithAcc(WACC);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Student> GetStudentWithAccAsync(string WACC) {
            return base.Channel.GetStudentWithAccAsync(WACC);
        }
        
        public WindowsFormsApplication1.ServiceReference1.Student GetStudentWithLikleyName(string LNAME) {
            return base.Channel.GetStudentWithLikleyName(LNAME);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Student> GetStudentWithLikleyNameAsync(string LNAME) {
            return base.Channel.GetStudentWithLikleyNameAsync(LNAME);
        }
    }
}
