//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.WebService.DataBasePart
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_students
    {
        public string st_acc { get; set; }
        public string st_name { get; set; }
        public string st_subject1 { get; set; }
        public string st_subject1_place { get; set; }
        public string st_subject2 { get; set; }
        public string st_subject2_place { get; set; }
        public string st_subject3 { get; set; }
        public string st_subject3_place { get; set; }
        public string st_subject4 { get; set; }
        public string st_subject4_place { get; set; }
        public string st_subject5 { get; set; }
        public string st_subject5_place { get; set; }
        public string st_subject6 { get; set; }
        public string st_subject6_place { get; set; }
        public string st_subject7 { get; set; }
        public string st_subject7_place { get; set; }
        public string st_subject8 { get; set; }
        public string st_subject8_place { get; set; }
    }
}
